# Webscrapping Assignment - 4

In [1]:
#importing necessary libraries
import selenium
import pandas as pd
from bs4 import BeautifulSoup
import time

#Importing requests
import requests

# importing regex
import re

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia:Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/You need to find following details:
- A) Rank
- B) Name
- C) Artist
- D) Upload date
- E) Views

In [2]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [3]:
#getting the specified url
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(3)

In [4]:
#Creating empty list
Rank = []
Name = []
Artist = []
Upload_date = []
Views = []

In [5]:
#Scraping data of rank details
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[1]")[:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')

In [6]:
#Scraping data of video names
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[2]")[:30]:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')

In [7]:
#Scraping data of artist name
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[3]")[:30]:
        Artist.append(i.text)
except NoSuchElementException:        
    Artist.append('-')

In [8]:
#Scraping data of upload dates
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[5]")[:30]:
        Upload_date.append(i.text)
except NoSuchElementException:        
    Upload_date.append('-')

In [9]:
#Scraping data of views
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[4]")[:30]:
        Views.append(i.text)
except NoSuchElementException:
    Views.append('-')

In [10]:
#DATA FRAMEING
Youtube=pd.DataFrame({})
Youtube['Rank'] = Rank
Youtube['Name'] = Name
Youtube['Artist'] = Artist
Youtube['Uploaded Date'] = Upload_date
Youtube['Views'] = Views

In [11]:
#Printing data frame
Youtube

,Rank,Name,Artist,Uploaded Date,Views
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,"June 17, 2016",9.20
1,2.,"""Despacito""[24]",Luis Fonsi,"January 12, 2017",7.50
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,"October 8, 2016",5.65
3,4.,"""Shape of You""[26]",Ed Sheeran,"January 30, 2017",5.43
4,5.,"""See You Again""[27]",Wiz Khalifa,"April 6, 2015",5.23
5,6.,"""Bath Song""[30]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.47
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[31]",Miroshka TV,"February 27, 2018",4.45
7,8.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.45
8,9.,"""Uptown Funk""[33]",Mark Ronson,"November 19, 2014",4.27
9,10.,"""Gangnam Style""[34]",Psy,"July 15, 2012",4.16
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,"March 6, 2014",4.10
11,12.,"""Dame Tu Cosita""[37]",El Chombo,"April 5, 2018",3.54
12,13.,"""Sugar""[38]",Maroon 5,"January 14, 2015",3.54
13,14.,"""Sorry""[39]",Justin Bieber,"October 22, 2015",3.46
14,15.,"""Roar""[40]",Katy Perry,"September 5, 2013",3.41
15,16.,"""Counting Stars""[41]",OneRepublic,"May 31, 2013",3.37
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,"October 7, 2014",3.31
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.23
18,19.,"""Dark Horse""[44]",Katy Perry,"February 20, 2014",3.13
19,20.,"""Faded""[45]",Alan Walker,"December 3, 2015",3.12
20,21.,"""Girls Like You""[46]",Maroon 5,"May 31, 2018",3.10
21,22.,"""Shake It Off""[47]",Taylor Swift,"August 18, 2014",3.09
22,23.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.08
23,24.,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.08
24,25.,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.06
25,26.,"""Mi Gente""[51]",J Balvin,"June 29, 2017",2.96
26,27.,"""Axel F""[52]",Crazy Frog,"June 16, 2009",2.95
27,28.,"""Perfect""[53]",Ed Sheeran,"November 9, 2017",2.93
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,"June 4, 2010",2.92
29,30.,"""Hello""[55]",Adele,"October 22, 2015",2.87

# 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details:
- A) Match title (I.e. 1st ODI)
- B) Series
- C) Place
- D) Date
- E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [12]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [13]:
#getting the specified url
url = "https://www.bcci.tv/"
driver.get(url)
time.sleep(3)

In [14]:
#Getting url for international fixture and clicking on it
Options_btn = driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']").click()

Infix_btn = driver.find_element_by_xpath("//a[@class='navigation__link navigation__link--in-drop-down']").click()
time.sleep(5)

In [15]:
#Creating empty list
Match_title = []
Series = []
Place = []
Date = []
Time = []

In [16]:
#Scraping data of match title
for i in driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']"):
    Match_title.append(i.text)
    
#Scraping data of Place
for i in driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span"):
    Place.append(i.text)
    
#for scraping date and time we have go into each title    
#Scraping url for each match
mat_url = []
urls = driver.find_elements_by_xpath("//div[@class='js-list']//a")
for i in urls:
    mat_url.append(i.get_attribute("href"))
    
#Now scraping date, time and series
for i in mat_url:
    driver.get(i)
    time.sleep(8)
    
    
    #Scraping data of Series
    try:
        series = driver.find_element_by_xpath("/html/body/div[2]/div/div[2]/section[3]/div/ul/li[1]/span[2]")
        Series.append(series.text)
    except NoSuchElementException:
        Series.append('-')
        
    #Scraping data of dates
    try:
        date = driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']//strong")
        Date.append(date.text)
    except NoSuchElementException:
        Date.append('-')
        
    #Scraping data of time
    try:
        times = driver.find_element_by_xpath("//span[@class='mc-header-scorebox__ist-time']")
        Time.append(times.text)
    except NoSuchElementException:
        Time.append('-')

In [17]:
#DATA FRAMEING
BCCI=pd.DataFrame({})
BCCI['Match Title'] = Match_title
BCCI['Series'] = Series
BCCI['Place'] = Place
BCCI['Date'] = Date
BCCI['Time'] = Time

In [18]:
#Printing data frame
BCCI

,Match Title,Series,Place,Date,Time
0,4th Test,-,"The Oval, London",-,-
1,5th Test,England v India 2021,"Old Trafford, Manchester",Friday 10 September,15:30 IST
2,Match 16,2021 ICC Men's T20 World Cup,"Dubai International Cricket Stadium, Dubai",Sunday 24 October,19:30 IST
3,Match 28,2021 ICC Men's T20 World Cup,"Dubai International Cricket Stadium, Dubai",Sunday 31 October,19:30 IST
4,Match 33,2021 ICC Men's T20 World Cup,"Sheikh Zayed Cricket Stadium, Abu Dhabi",Wednesday 3 November,19:30 IST
5,Match 37,-,"Dubai International Cricket Stadium, Dubai",Friday 5 November,19:30 IST
6,Match 42,-,"Dubai International Cricket Stadium, Dubai",Monday 8 November,19:30 IST

# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details:
- A) Name
- B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [19]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [20]:
#getting the specified url
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(3)

In [22]:
#Going to search bar and searching for selenium exception
ser_bar = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
ser_bar.send_keys("selenium exception handling")
ser_but = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button").click()
time.sleep(3)

In [23]:
#Url of selenium exception handling page
urls = driver.find_element_by_xpath("//div[@class='gsc-expansionArea']//div//a")
page_url = urls.get_attribute("href")

driver.get(page_url)
time.sleep(5)

#Scraping data of names of exceptions
Name = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[1]")[1:]:
    Name.append(i.text)
    
#Scraping data of descriptions of exceptions  
Description = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[2]")[1:]:
    Description.append(i.text)

In [24]:
#DATA FRAMEING
Guru=pd.DataFrame({})
Guru['Name of Exception'] = Name
Guru['Description of Exception'] = Description

In [25]:
#Printing data frame
Guru

,Name of Exception,Description of Exception
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ You have to find following details:
- A) Rank
- B) State
- C) GSDP at current price (19-20)
- D) GSDP at current price (18-19)
- E) Share(18-19)
- F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [26]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [27]:
#getting the specified url
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(3)

In [28]:
#Clicking on economy section
economy = driver.find_element_by_xpath("//div[@class='navbar']//div[2]//button").click()

urls = driver.find_element_by_xpath("//div[@class='dropdown-content']//a[3]")
ineco_page = urls.get_attribute("href")
#Going to indian economy page
driver.get(ineco_page)  
time.sleep(5)

In [29]:
#Creating empty list
Rank = []
State = []
GSDP_1 = []
GSDP_2 = []
Share = []
GDP = []

In [30]:
#get the url of page containing GDP of indian states
sta_GDP = driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a")
GDP_url = sta_GDP.get_attribute("href")

driver.get(GDP_url)
time.sleep(6)


#Scraping data of rank
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[1]"):
    Rank.append(i.text)

    
#Scraping data of state name
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[2]"):
    State.append(i.text)

    
# Scraping data of GSDP at current price (19-20)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[3]"):
    GSDP_1.append(i.text)

    
#Scraping data of GSDP at current price (18-19)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[4]"):
    GSDP_2.append(i.text)

    
#Scraping data of Share(18-19)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[5]"):
    Share.append(i.text)

    
#Scraping data of GDP($ billion)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[6]"):
    GDP.append(i.text)

In [31]:
#DATA FRAMEING
StatisticsTime=pd.DataFrame({})
StatisticsTime['Rank'] = Rank
StatisticsTime['State'] = State
StatisticsTime['GSDP at current price (19-20)'] = GSDP_1
StatisticsTime['GSDP at current price (18-19)'] = GSDP_2
StatisticsTime['Share(18-19)'] = Share
StatisticsTime['GDP($ billion)'] = GDP

In [32]:
#Printing the data frame
StatisticsTime

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/ You have to find the following details:
- A) Repository title
- B) Repository description
- C) Contributors count
- D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [33]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [34]:
#getting the specified url
url = "https://github.com/"
driver.get(url)
time.sleep(3)

In [35]:
#Getting explore button and clicking on it
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()

#Selecting trending option
trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [36]:
#Creating empty list
repo_urls = []
rep_title = []
Description = []
Contributors = []
Language = []
lang = []

In [37]:
#Fetching urls for each repository
repository = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    repo_urls.append(i.get_attribute("href"))

    
#Scraping data of repository title
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    rep_title.append(i.text)

    
#Scraping data from every repository page
for i in repo_urls:
    driver.get(i)
    time.sleep(3)
    
    
    #Scraping data of decription
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    #Scraping data of contributors
    try:
        cont_tags = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(cont_tags.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
    #fetching Languages used
    try:
        for i in driver.find_elements_by_xpath("//span[@class='color-text-primary text-bold mr-1']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')

In [38]:
#DATA FRAMEING
Github=pd.DataFrame({})
Github['Repository title'] = rep_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language

In [39]:
#Printing data frame
Github

,Repository title,Repository description,Contributors count,Language used
0,VickScarlet / lifeRestart,やり直すんだ。そして、次はうまくやる。,11,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
1,GTAmodding / re3,"GTA III, Vice City",41,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
2,TheAlgorithms / C-Plus-Plus,Collection of various algorithms in mathematic...,234,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
3,microsoft / PowerToys,Windows system utilities to maximize productivity,203,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
4,bespoyasov / frontend-clean-architecture,React + TypeScript app built using clean archi...,2,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
5,TheAlgorithms / Javascript,A repository for All algorithms implemented in...,152,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
6,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,110,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
7,khanhas / spicetify-cli,Commandline tool to customize Spotify client. ...,26,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
8,metaplex-foundation / metaplex,Protocol and application framework for decentr...,35,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
9,TheAlgorithms / Python,All Algorithms implemented in Python,714,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
10,HashLips / generative-art-opensource,Create generative art by using the canvas api ...,-,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
11,vxunderground / MalwareSourceCode,Collection of malware source code for a variet...,4,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
12,AakashKumarNain / annotated_research_papers,This repo contains annotated research papers t...,2,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
13,mathaou / termdbms,A TUI for viewing and (eventually) editing dat...,3,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
14,DiegoVicen / som-tsp,Solving the Traveling Salesman Problem using S...,3,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
15,bpierre / loot-rarity,💠 Rarity levels for Loot.,-,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
16,solana-labs / dapp-scaffold,Scaffolding for a dapp built on Solana,13,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
17,Anish-Agnihotri / dhof-loot,Scripts to collect statistics about LOOT + der...,2,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
18,SeanDaBlack / AbBOT,-,8,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
19,willmcgugan / textual,Textual is a TUI (Text User Interface) framewo...,12,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
20,HowProgrammingWorks / Index,Metarhia educational program index 📖,18,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
21,v2fly / v2ray-core,A platform for building proxies to bypass netw...,107,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
22,dblalock / bolt,10x faster matrix and vector operations.,2,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
23,Vonng / ddia,《Designing Data-Intensive Application》DDIA中文翻译,53,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."
24,LunarVim / LunarVim,An IDE layer for Neovim with sane defaults. Co...,154,"[JavaScript, CSS, HTML, C++, C, Assembly, CMak..."

# 6. Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/ You have to find the following details:
- A) Song name
- B) Artist name
- C) Last week rank
- D) Peak rank
- E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [2]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [3]:
#getting the specified url
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(3)

In [4]:
#Clicking on charts
charts=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/header/div/ul/li[1]").click()

In [5]:
#Creating empty list
Name = []
Artist = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [6]:
#Getting url for top 100 
urls = driver.find_element_by_xpath("//div[@class='charts-landing first-group']//div//a")
page_url = urls.get_attribute("href")
driver.get(page_url)
time.sleep(4)


#Now we have to extract required info from page url
#Scraping data of song names
for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']"):
    Name.append(i.text)

    
#Scraping data of artist names
for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']"):
    Artist.append(i.text)

    
#Scraping data of last week ranks
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']"):
    Last_week_rank.append(i.text)

    
#Scraping data of peak rank
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']"):
    Peak_rank.append(i.text)

    
#Scraping data of weeks on board
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']"):
    Weeks_on_board.append(i.text)

In [7]:
#DATA FRAMEING
Billboard=pd.DataFrame({})
Billboard['Name'] = Name
Billboard['Artist'] = Artist
Billboard['Last week rank'] = Last_week_rank
Billboard['Peak rank'] = Peak_rank
Billboard['Weeks on board'] = Weeks_on_board

In [8]:
#Printing the dataframe
Billboard

,Name,Artist,Last week rank,Peak rank,Weeks on board
0,Stay,The Kid LAROI & Justin Bieber,1,1,7
1,Bad Habits,Ed Sheeran,2,2,9
2,Good 4 U,Olivia Rodrigo,3,1,15
3,Kiss Me More,Doja Cat Featuring SZA,5,3,20
4,Industry Baby,Lil Nas X & Jack Harlow,7,2,5
...,...,...,...,...,...
95,Tick Tock,Young Thug,-,96,1
96,Permission To Dance,BTS,66,1,7
97,AM,Nio Garcia X J Balvin X Bad Bunny,85,41,9
98,Time Heals,Rod Wave,-,99,1
99,Thinking 'Bout You,Dustin Lynch Featuring Lauren Alaina Or MacKen...,91,91,2

# 7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/ You have to find the following details:
- A) Name
- B) Designation
- C) Company
- D) Skills they hire for
- E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and 
click on search. All this should be done through code

In [2]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [3]:
#getting the specified url
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(3)

In [4]:
#Fetching urls for recruiter page
rec = driver.find_element_by_xpath("//a[@title='Search Recruiters']")
page_url = rec.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [5]:
#Fetching search button,bar xpath and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
but = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()     
time.sleep(4)

In [6]:
#Creating empty list
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [7]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']")[:50]:
    Name.append(i.text)
time.sleep(5)


#Scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']")[:50]:
    Designation.append(i.text)
time.sleep(5)

#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]")[:50]:
    Company.append(i.text)
time.sleep(5)
    
#scraping data of Skills 
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")[:50]:
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
    time.sleep(5)

#Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span")[:50]:
    Location.append(i.text)
time.sleep(5)

In [8]:
#DATA FRAMEING
Naukri=pd.DataFrame({})
Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Skills'] = Skills
Naukri['Location'] = Location

In [9]:
#Printing data frame
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Anik Agrawal
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehousing, ET...",Company Recruiter
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Ahmedabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",subhas patel
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Founder CEO
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",UK - (london)
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Recruitment Lead Consultant
17,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Vadodara / Baroda
18,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Institute for Financial Management and Resear
19,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Programme Manager
20,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Chennai
21,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Balu Ramesh
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",HR Administrator
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Trivandrum
24,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Asif Lucknowi
25,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Director
26,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Indore
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",InstaFinancials
28,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Human Resource
29,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Priyanka Akiri
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",HR Manager
32,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad
33,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,Kalpana Dumpala
34,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Executive Hiring
35,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Hyderabad / Secunderabad
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Mubarak
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Company HR
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Bengaluru / Bangalore
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Kushal Rastogi
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Company HR
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Ruchi Dhote
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Senior Executive Talent Acquisition
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Pune
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Mahesh Babu Channa
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",HR Team Lead
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Hyderabad / Secunderabad
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Kapil Devang
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",HR Manager

Above is the scraped data of Question 7. And i have scrapped it using selenium.

# 8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/ You have to find the following details:
- A) Book name
- B) Author name
- C) Volumes sold
- D) Publisher
- E) Genre

In [10]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [11]:
#getting the specified url
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver.get(url)
time.sleep(3)

In [12]:
#Creating empty list
Book_name = []
Author = []
Volumes_sold = []
Publisher = []
Genre = []

In [13]:
#scraping data of book names
for i in driver.find_elements_by_xpath("//tbody//tr/td[2]"):
    Book_name.append(i.text)

    
#Scraping data of author names
for i in driver.find_elements_by_xpath("//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author.append(i.text)
    except NoSuchElementException:
        Author.append('-')
time.sleep(1)


#Scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody/tr/td[4]"):
    Volumes_sold.append(i.text)

    
#Scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody/tr/td[5]"):
    Publisher.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//tbody/tr/td[6]"):
    Genre.append(i.text)

In [15]:
#DATA FRAMEING
Novel=pd.DataFrame({})
Novel['Book Name'] = Book_name
Novel['Author'] = Author
Novel['Volume sold'] = Volumes_sold
Novel['Publisher'] = Publisher
Novel['Genre'] = Genre

In [16]:
#Printing data frame
Novel

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:
- A) Name
- B) Year span
- C) Genre
- D) Run time
- E) Ratings
- F) Votes

In [17]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [18]:
#getting the specified url
url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)
time.sleep(3)

In [19]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [20]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

    
#Scraping data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)

    
#Scraping data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)

    
#Scraping data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)

    
#Scraping data of votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [21]:
#DATA FRAMEING
IMDB=pd.DataFrame({})
IMDB['Name'] = Name
IMDB['Year Span'] = Year_span
IMDB['Genre'] = Genre
IMDB['Run Time'] = Run_time
IMDB['Ratings'] = Ratings
IMDB['Votes'] = Votes

In [22]:
#Printing data frame
IMDB

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,867,187"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"902,795"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"894,430"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"269,214"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"229,467"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,478"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,355"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"174,334"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,480"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"198,158"

# 10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ You have to find the following details:
- A) Dataset name
- B) Data type
- C) Task
- D) Attribute type
- E) No of instances
- F) No of attribute
- G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

In [2]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [3]:
#getting the specified url
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(3)

In [4]:
#Finding view all dataset button
view_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")    
page_url = view_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(5)

#Getting page urls containing list of all datasets
all_lst = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
lst_url = all_lst.get_attribute("href")           
driver.get(lst_url)
time.sleep(5)

#fetching url for each dataset
data_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")    

urls = []     
for i in data_url:
    urls.append(i.get_attribute("href"))

In [5]:
#Creating empty list
Data_name = []
Data_type = []
Task = []
Attr_type = []
Instances = []
n_attributes = []
Year = []

In [6]:
#Scraping requiredinfo from urls
for i in urls:
    driver.get(i)
    time.sleep(3)
    
    
    #Scraping Dataset name
    try: 
        ds_name = driver.find_element_by_xpath("//span[@class='heading']")
        Data_name.append(ds_name.text)
    except NoSuchElementException:
        Data_name.append('-')
    time.sleep(1)
    
    
    #Scraping data type
    try:
        dtype = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[2]")
        if dtype.text == "N/A": raise NoSuchElementException
        Data_type.append(dtype.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(1)
    
    
    #Scraping Attribute type
    try:
        atype = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[2]")
        if atype.text == "N/A": raise NoSuchElementException
        Attr_type.append(atype.text)
    except NoSuchElementException:
        Attr_type.append('-')
    time.sleep(1)
    
    
    #scraping Task
    try:
        task = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(1)
    
    
    #Scraping No of instances
    try:
        inst = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[4]")
        if inst.text == "N/A": raise NoSuchElementException
        Instances.append(inst.text)
    except NoSuchElementException:
        Instances.append('-')
    time.sleep(1)
    
    
    #Scraping  No of attribute
    try:
        attr = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[4]")
        if attr.text == "N/A": raise NoSuchElementException
        n_attributes.append(attr.text)
    except NoSuchElementException:
        n_attributes.append('-')
    time.sleep(1)
    
    
    #scraping year
    try:
        year = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(1)

In [7]:
#DATA FRAMEING
UCI=pd.DataFrame({})
UCI['Data Name'] = Data_name
UCI['Data Type'] = Data_type
UCI['Task'] = Task
UCI['Attribute type'] = Attr_type
UCI['No of instance'] = Instances
UCI['No of attributes'] = n_attributes
UCI['Year'] = Year

In [8]:
#Printing dataframe
UCI

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
4,A study of Asian Religious and Biblical Texts ...,"Multivariate, Text","Classification, Clustering",Integer,590,8265,2019
...,...,...,...,...,...,...,...
583,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
584,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
585,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
586,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
587,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990